version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
    environment:
      - node.name=es01
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  logstash:
    image: docker.elastic.co/logstash/logstash:7.11.1
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5044:5044
  filebeat:
    image: filebeat
    build:
      context: .
      dockerfile: Dockerfile.Filebeat
    volumes:
      - filebeatdata:/usr/share/filebeat/logs
  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    ports:
      - 5601:5601
volumes:
  esdata:
    driver: local
  filebeatdata:
    driver: local
