name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the docker-compose stack
      run: docker-compose up -d --build
    - uses: jakejarvis/wait-action@master
    - name: 1min pls
      with:
        time: '60s'
    - uses: actions/checkout@v1
    - name: Check running containers
      run: docker ps -a
    - name: Check logs
      run: docker logs elasticsearch
    - name: Run test ES
      run: docker exec -i elasticsearch curl -I localhost:9200
