name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Fix vm.max_map_count
      run: sysctl -w vm.max_map_count=262144
      
    - name: Build the docker-compose stack
      run: docker-compose up -d --build
      
    - name: Check running containers
      run: docker ps -a

    - name: Run test Kibana
      run: docker exec -i elasticstack_kibana_1 curl -I 0.0.0.0:5601
